# Generated by Django 5.0.2 on 2024-07-27 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='privatemessage',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver', 'timestamp'), name='unique_message'),
        ),
    ]
