# Generated by Django 5.0.2 on 2024-03-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='chapter',
            new_name='lecture_chapter',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='lecture',
        ),
    ]
