# Generated by Django 5.0.2 on 2024-04-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='lecture',
        ),
    ]
