# Generated by Django 5.0.2 on 2024-03-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_rename_chapter_uploadfile_lecture_chapter_and_more'),
        ('user', '0006_remove_lecturechapter_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='lecture_chapter',
            new_name='chapter',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='user.lecturechapter'),
        ),
    ]
