# Generated by Django 5.0.2 on 2024-03-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='user.lecture')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
