# Generated by Django 5.0.2 on 2024-03-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_lecture_lecturechapter_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturechapter',
            options={'verbose_name_plural': 'Lecture Chapters'},
        ),
        migrations.RemoveField(
            model_name='lecturechapter',
            name='title',
        ),
    ]
