# Generated by Django 5.0.2 on 2024-04-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_study_timersession_elapsed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_timersession',
            name='records',
            field=models.TimeField(),
        ),
    ]
