# Generated by Django 5.0.2 on 2024-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_study_timersession_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_timersession',
            name='is_reset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study_timersession',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study_timersession',
            name='is_stopped',
            field=models.BooleanField(default=True),
        ),
    ]
