# Generated by Django 5.0.2 on 2024-04-13 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_study_timersession_is_reset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_timersession',
            name='is_reset',
        ),
        migrations.RemoveField(
            model_name='study_timersession',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='study_timersession',
            name='is_stopped',
        ),
        migrations.AddField(
            model_name='study_timersession',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study_timersession',
            name='goalpercent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
