# Generated by Django 5.0.2 on 2024-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_study_timersession_is_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_timersession',
            name='elapsed_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='study_timersession',
            name='goal_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='study_timersession',
            name='records',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='study_timersession',
            name='remaining_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
