# Generated by Django 5.0.2 on 2024-04-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_lecture_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='user',
        ),
    ]
